server:
    port: ${SERVER_PORT}
spring:
    application:
        name: list of products
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/list_of_products
        username: ${DATABASE_USER:postgres}
        password: ${DATABASE_PASSWORD}
    jpa:
        generate-ddl: false
        show-sql: ${SHOW_SQL:false}
        properties:
            hibernate:
                ddl-auto: none
                jdbc:
                    lob:
                        non_contextual_creation: true
                dialect: org.hibernate.dialect.PostgreSQLDialect